project_id_env: GM9I_CROWDIN_ID
api_token_env: CROWDIN_TOKEN
preserve_hierarchy: true

files:
  - source: /nitrofiles/languages/en-US/language.ini
    translation: /nitrofiles/languages/%locale%/language.ini
